DROP TABLE IF EXISTS books;

CREATE TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
AUTHOR_ID INT NOT NULL,
title VARCHAR(250) NOT NULL,
PRICE_OLD VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);